# Sets some default verbose
#
#/control/verbose 2
#/control/saveHistory
#/run/verbose 2
#
# Use this open statement to create an OpenGL view:
/vis/open OGLIQt

/vis/viewer/set/autoRefresh false
/vis/verbose errors

#/vis/drawVolume

#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
#/vis/modeling/trajectories/create/drawByCharge
#/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
#/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 5
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)


/vis/scene/add/hits

/vis/filtering/trajectories/create/particleFilter
/vis/filtering/trajectories/particleFilter-0/add gamma
/vis/filtering/trajectories/particleFilter-0/add e-
/vis/filtering/trajectories/particleFilter-0/invert true

/vis/scene/endOfEventAction accumulate

/vis/viewer/set/autoRefresh true
/vis/verbose warnings


## Particle colors

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma yellow
/vis/modeling/trajectories/drawByParticleID-0/set e- red
/vis/modeling/trajectories/drawByParticleID-0/set e+ blue
/vis/modeling/trajectories/drawByParticleID-0/set pi- white
/vis/modeling/trajectories/drawByParticleID-0/set pi+ magenta
/vis/modeling/trajectories/drawByParticleID-0/set mu- green
/vis/modeling/trajectories/drawByParticleID-0/setRGBA mu- 1 0.65 0 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA nu_mu 0.1 0.1 0.4 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA nu_e 0.1 0.1 0.4 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_nu_mu 0.1 0.1 0.4 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA anti_nu_e 0.1 0.1 0.4 1
/vis/modeling/trajectories/drawByParticleID-0/setRGBA neutron 0.1 0.1 0.1 1
/vis/modeling/trajectories/drawByParticleID-0/set ion cyan

/control/verbose 2
/control/saveHistory
/run/verbose 2

/vis/viewer/set/style surface
/vis/viewer/set/edge 0
#/vis/viewer/set/viewpointThetaPhi 130 20

/vis/viewer/set/viewpointVector 1 1 1
#/vis/viewer/set/background white
